### ISSUE TITLE
Estructura del repositorio

### ISSUE THREAD

**Issue by Peque** [python-vigo/charlas#3]
Propongo que todas las charlas estén en la raíz para un acceso más directo. Ejemplo:

```
20180101 - Python Vigo - Título de la presentación [relámpago]
```

Incluso quitaría "Python Vigo" o "PyDay". Esta información puede estar en el README de cada carpeta, junto con información sobre los ponentes.

Update
---------

Me ofrezco a hacer el cambio si se aprueba.

**Comment by Peque** [comment]
Creo que además así se facilitan los "pull requests".

Haciendo el primero he tenido que copiar una estructura que me ha parecido compleja (4 niveles de carpetas hasta llegar al contenido de la presentación). Y varios READMEs por el camino.

**Comment by Peibolvig** [comment]
La verdad es que puede tener sentido.

Esa opción que propones simplifica bastante la estructura, y en el caso de que se quiera tener clasificado el contenido de alguna forma más completa/compleja, quizás se puede solucionar fácilmente con una tabla/índice con la estructura que se quiera (por ejemplo en el README principal).

La idea inicial detrás de esa estructura compleja de carpetas es simplemente que la gente pueda llegar al material de una charla en base a "lo que recuerde de ella".
Lo típico de "Cómo era aquella charla que dio Miguel...?" o "Cómo era aquella charla que vi en el PyDay de 2017?"...

Lo dicho, con que esa información esté en un índice podría bastar.

Una modificación que propuso ayer  @daniel-at-github fue que la fecha la pongamos en formato ISO, que es igual que ahora pero con guiones separando año, mes y día.

Así que por mi haríamos lo siguiente:

- Darle una vuelta al índice actual del README principal para incluir la meta-información de las charlas  que sea útil para esa búsqueda inicial de una charla puntual que pueda interesar a alguien (evento, tipo de charla,...).

- Cambiar la estructura de carpetas por la que propones pero dejando los nombres de carpeta así:

```
Fecha ISO - Título [tipo]

2018-12-31 - Título de la presentación [relámpago]
```

Yo por mi haría ya el cambio, no hay mucho contenido, y si después la gente se pronuncia y no le gusta el formato, será fácil volver atrás o hacer otra cosa.

Así que tomemos la vía proactiva. Si te cuadran los ajustes que propongo a tu sugerencia, adelante con ello.

Dejo el issue abierto para que la gente pueda comentar si tiene alguna sugerencia o modificación a mayores ;)

**Comment by Peibolvig** [comment]
Pues no lo había pensado, pero si la información relevante va en el propio título de la carpeta, no sería necesario índice :smiley: !!

> * Y viniéndonos arriba generaría el índice a partir de los nombres de las carpetas. Y aún más, metería integración continua para chequear que el formato del nombre de la carpeta está bien al subirlo, por chulear. :nerd_face:

No te diría yo que no molaría eso :laughing: Si alguien se anima a hacerlo... ;)

Eso sí, si hay que elegir entre dedicar esfuerzo a CI o a arqueología de charlas, casi le daría más peso a esto último por ahora, jeje.

Creo que la estructura que propones con el nombre del ponente es bastante completa y ya contiene toda la información que contiene el índice actual.

Lo único que diría con respecto al nombre del ponente es que lo ideal sería que un mismo ponente siempre tuviera el mismo "identificador", es decir, que no aparezca en algunas charlas "Pepe López", en otra "Pepe L. Rodríguez", en otra "Pepillo".

+1 a la estructura que propone @cua-cua

> '2018-01-01 - Nombre ponente - Título de la presentación [relámpago]'

**Comment by Peibolvig** [comment]
Uno de los problemas que veo que tienen los nombres largos de carpetas es este:
![image](https://user-images.githubusercontent.com/1297980/51413209-65d01900-1b6e-11e9-9a72-70d8e556e46a.png)

Que si descargas el repositorio no hay problema, pero si su uso principal va a ser desde la propia web esa información de título, tipo... se pierde :cry:

**Comment by cua-cua** [comment]
> Lo único que diría con respecto al nombre del ponente es que lo ideal sería que un mismo ponente siempre tuviera el mismo "identificador", es decir, que no aparezca en algunas charlas "Pepe López", en otra "Pepe L. Rodríguez", en otra "Pepillo".

Nombre oficial y carnet de socio todo en uno al dar la primera charla :stuck_out_tongue_winking_eye:

**Comment by Peibolvig** [comment]
Reabro el issue, que se cerró sólo el al fusionar el pull request que estaba relacionado, pero vamos a dar unos días a la gente por si quiere aportar algo sobre este mismo issue.

Lo de pasar el ratón por encima no lo sabía! jajaja

La verdad es que teniendo la información con estructura definida en el título da un poco igual, porque si el día de mañana mucha gente decide que no le gusta esta estructura, sería fácil automatizar el proceso para ese cambio, creo que es un problema menor este de los títulos largos :smile:

**Comment by Peibolvig** [comment]
Ok, tras 12 días abierto, nadie dijo nada así que damos por buena la estructura. Si alguien tiene algo que decir, que abra otro issue y listo :)
